<?php $this->mainMenu()->setActiveItemId('cv');?>
<div class="row justify-content-md-center">
    <div class="col-md-10">  
        <div class="row">
            <div class="col-md-3">
                <div class="row justify-content-md-center badge-dark">
                    <div class="col-md-8 pt-3">
                        <img src="<?php echo $this->url('home'); ?>public/img/profile.png" class="card-img rounded-circle" alt="Praew" width="100px" >
                    </div>
                    <div class="col-md-12 pt-3">
                        <h6 class="text-center text-uppercase">Miss Aumaporn Tangmanosodsikul</h6>
                        <h6 class="text-center text-uppercase">Praew</h6>
                        <p class="text-center">Software Developer</p>
                    </div>
                </div> <!--image-->
                
                <div class="row justify-content-md-left badge-light pt-4 pl-3">
                    <ul class="list-unstyled small">
                        <li><b>Birthday:</b> 13 May 1987</li>
                        <li><b>Height:</b> 155 cm</li>
                        <li><b>Weight:</b> 60 kg</li>
                        <li><b>Nationality:</b> Thai</li>
                        <li><b>Religion:</b> Buddhism</li>
                        <li><b>Marital Status:</b> Single</li>
                    </ul>
                </div>
                
                <div class="row justify-content-md-left badge-light pt-4 pl-3" style="position: relative; bottom: 0px;">
                    <address class="small text-muted">
                        359/187 A-Space Sukhumvit<br>
                        2 77 Building, Onnuch Road,<br>
                        Suanluang, Bangkok 10250<br><br>
                        <abbr title="Phone">P:</abbr> 084-659-5073<br><br>
                        <a href="mailto:preawfah@hotmail.com">preawfah@hotmail.com</a>
                    </address>
                </div>  <!--address-->

            </div>
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <h6 class="text-uppercase">
                            Education
                        </h6>
                        <hr/>
                        <p class="small"><b>Bachelor:</b> May 2006 - Mar 2009, The University of the 
                            Thai Chamber of Commerce, Thailand, GPA.3.58 (First class honors), Major Computer Science</p>
                    </div>
                </div><!--Education-->
                
                <div class="row mt-3">
                    <div class="col-md-12">
                        <h6 class="text-uppercase">
                            Experience
                        </h6>
                        <hr/>
                        <div class="p-3 mb-2 bg-light text-dark small">
                            <div class="row">
                                <div class="col-md-6 text-left">
                                    Senior Developer at Common-services Co.,Ltd 
                                </div>
                                <div class="col-md-6 text-right">
                                    December 2013 - January 2020
                                </div>
                            </div>
                        </div>
                        <div>
                            <ul class="small">
                                <li>Providing Project Management, PHP Development for the Feed.biz website</li>
                                <li>Created/Consuming Web Services coding in using SOAP, REST, XML Technologies</li>
                                <li>Validated XML input versus XSD to ensure lead data accuracy</li>
                                <li>Database Design and Query Optimization (Worked in backend with MySQL)</li>
                                <li>Developed PDO Prepared Statements</li>
                                <li>Designed applications in AJAX with rich user interfaces</li>
                                <li>Worked on Apache Server, Linux</li>
                                <li>Troubleshooting Daily Incidents & CodeIgniter based MVC Application Support as well
                                as maintaining them</li>
                                <li>Implemented the marketplaces feed submission module (Prestashop, Shopify) for
                                Amazon, Cdiscount, Google Shopping and Mirakl</li>
                                <li>Source control and release management using GIT</li>
                                <li>Worked on XAMPP using the PHP based CodeIgniter MVC framework, Node.js
                                    And REACT.js</li>
                            </ul>
                        </div><!--COMMON-->
                        
                        <div class="p-3 mb-2 bg-light text-dark small">
                            <div class="row">
                                <div class="col-md-6 text-left">
                                    PHP Developer at Diversition Co., Ltd.
                                </div>
                                <div class="col-md-6 text-right">
                                    2011 - November 2013
                                </div>
                            </div>
                        </div>
                        <div>
                            <ul class="small">
                                <li>Developed Object Oriented PHP application</li>
                                <li>Developed different system modules e.g Selection, Order, Material Receive and
                                Invoice</li>
                                <li>Designed different front end forms using Drupal and CSS</li>
                                <li>Maintaining User groups with Drupal CMS.</li>
                            </ul>
                        </div><!--COMMON-->
                        
                    </div>
                </div><!--Experience-->
                
            </div>
        </div>
    </div>
</div>