<?php $this->mainMenu()->setActiveItemId('line');?>

<div class="row text-center">
    <div class="col-md-12 small">
        Assignment : <?= $this->todo_api['line']; ?><br/>  
    </div>
</div><hr/>

<div class="row p-3 justify-content-lg-center">
    <div class="col-md-3 text-center mb-3">
        <div id="lineSlide" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#ex1" data-slide-to="0" class="active"></li>
                <li data-target="#ex2" data-slide-to="1"></li>
                <li data-target="#ex3" data-slide-to="2"></li>
                <li data-target="#ex4" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="<?php echo $this->url('home'); ?>public/img/line-screen-short/add-1.png" class="d-block w-100">
                </div>
                <div class="carousel-item">
                  <img src="<?php echo $this->url('home'); ?>public/img/line-screen-short/add-2.png" class="d-block w-100">
                </div>
                <div class="carousel-item">
                  <img src="<?php echo $this->url('home'); ?>public/img/line-screen-short/add-3.png" class="d-block w-100">
                </div>
                <div class="carousel-item">
                  <img src="<?php echo $this->url('home'); ?>public/img/line-screen-short/noti.png" class="d-block w-100">
                </div>
              </div>
              <a class="carousel-control-prev" href="#lineSlide" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#lineSlide" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
        </div>
    </div><!--slide-->
    
    <div class="col-md-6">
        <div class="font-weight-lighter pb-3">
            <p>GIT URL : 
                <a href="https://github.com/praewfah/bot-line" target="_blank">https://github.com/praewfah/bot-line</a>
            </p>
            <p>Please see the result on the slide show</p>
            <ul class="">
                <li>My chat bot's name "เลขมงคล"</li>
                <li>After add fried to "เลขมงคล", you can chat with the line chat bot</li>
                <li>When the Line Bot can not answer a question to the customer more than 10 second, 
                    the line group "Notification เลขมงคล" will getting a notification</li>
            </ul>
        </div>
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <img src="<?php echo $this->url('home'); ?>public/img/qr_code.png" class="card-img" alt="Scan me!">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title font-weight-lighter">QR code for chat bot "เลขมงคล"</h5>
                        <p class="card-text small">Scan this QR code with LINE to add LINE Official Account as a friend.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <img src="<?php echo $this->url('home'); ?>public/img/line_notification.jpg" class="card-img" alt="Try me!">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title font-weight-lighter">QR code for "Notification เลขมงคล"</h5>
                        <p class="card-text small">Scan this QR code with LINE to add to group of notification.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>