<footer class="bd-footer">
  <div class="container-fluid p-md-5">
    <ul id="footer-menu" class="nav justify-content-md-center">
        <li class="nav-item">
            <a class="nav-link active" href="<?= $this->url('home') ?>">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="<?= $this->url('google') ?>">Google API</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="<?= $this->url('line') ?>">Line API</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="<?= $this->url('doscg', ['action'=>'api', 'id'=>'xyz']) ?>">Function xyz</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="<?= $this->url('doscg', ['action'=>'api', 'id'=>'bc']) ?>">Function bc</a>
        </li>
    </ul>
    <div>
        Designed and built by <a href="<?php echo $this->url('cv'); ?>">Aumaporn Tangmanosodsikul</a>, 
        GIT URL 
        <a href="https://github.com/praewfah/SCG_ZF3_PHP.git" target="_blank" rel="license noopener">
            https://github.com/praewfah/SCG_ZF3_PHP.git
        </a><br/>
        References : 
        <a href="https://github.com/Tonytoons/PHP-ZF3-Starter-Kit" target="_blank">
            ZF3 Framework (PHP)
        </a>
    </div>
  </div>
</footer>

<input id="base_url" value="<?php echo $this->url('home'); ?>" type="hidden">

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 
<!-- Vue.js -->
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-resource@1.5.1"></script>

<script src="<?php echo $this->url('home'); ?>public/js/doscg.js" onLoad="init();" defer></script>