<header class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #a71219;">
    <a class="navbar-brand" href="#">DOSCG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <?php   
                $this->mainMenu()->setItems(include_once CONFIG_PATH . 'menu.config.php');
                echo $this->mainMenu()->render(); 
            ?>
        </ul>
        <span class="navbar-text">
            SCG Technology Developer Assignment March 2020
        </span>
    </div>
</header>