<?php echo $this->doctype(); ?>
<html lang="en"> 
    <head>
        <meta http-equiv="content-TYPE" content="text/html; charset=UTF-8">
        <meta http-equiv="Cache-control" content="public">
        <meta http-equiv="EXPIRES" content="<?php echo gmdate("D, d M Y H:i:s", time() + (60*60)) . " GMT"; ?>">
        <meta http-equiv="cleartype" content="on">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
        <meta name="MobileOptimized" content="767">
        <meta name="HandheldFriendly" content="True">
        <meta name='mobile-web-app-capable' content='yes'>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable = no">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="<?php echo $this->url('home'); ?>img/icon/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
        <meta name='application-name' content='ZF3'>
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name='apple-mobile-web-app-status-bar-style' content='black'>
        <meta name='apple-mobile-web-app-title' content='ZF3'>
        <meta name="AUTHOR" content="Tonytoons">
        <meta name="revisit-after" content="7 days">
        <meta name="COPYRIGHT" content="&copy; <?php echo date('Y') ?> ZF3">
        <link rel="shortcut icon" href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico" type="image/x-icon">
        <link rel="icon" href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico" type="image/x-icon">
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->url('home'); ?>img/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->url('home'); ?>img/favicon/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico">
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico">
        <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico">
        <link rel="icon" type="image/png" sizes="16x16" href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico">
        <link rel="manifest" href="<?php echo $this->url('home'); ?>manifest.json">
        <link rel="apple-touch-startup-image" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-180x180.png">
        
        <!--bootstrap 4.4.1-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        
        <?php include_once 'css.phtml'; ?>
        
        <title>DOSCG</title>
    </head>
    <body>
        <?php include_once 'header.phtml'; ?>
        <main class="bd-masthead" id="content" role="main">
            <div class="container pt-5">
              <div class="row pt-5">
                <div class="col-12 mx-auto col-md-12"> 
                    <?php echo $this->content; ?>
                </div>
                </div>
            </div>
        </main>
        <?php include_once 'footer.phtml'; ?>
    </body>
</html>